title = "Sai Pavan's blog"
languageCode = "en-us"
baseurl = "https://usaipavan.github.io/"
copyright = "(c) 2016 Sai Pavan."
disqusShortname = "usaipavan"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
Paginate = 2

[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"
  
[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
[params]
    Author = "Sai Pavan"    
	sidebartitle = "Sai Pavan's blog"
	sidebartagline = "My tryst with .net and software programming in general"
[[menu.main]]
    name = "About"
    url = "/about"
[[menu.social]]
	pre = "<i class='fa fa-twitter fa-lg fa-fw' target='_blank'></i>"
    url = "https://twitter.com/usaipavan"
    identifier = "twitter"
[[menu.social]]
    pre = "<i class='fa fa-linkedin fa-lg fa-fw'></i>"
    url = "https://www.linkedin.com/in/usaipavan"
    identifier = "linkedin"
[[menu.social]]
    pre = "<i class='fa fa-rss fa-lg fa-fw'></i>"
    url = "/index.xml"
    identifier = "rss"